# Generated by Django 3.2.19 on 2023-06-21 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения митапа')),
                ('start', models.DateField(verbose_name='Начало митапа')),
                ('end', models.DateField(verbose_name='Окончание митапа')),
            ],
            options={
                'verbose_name': 'Митап',
                'verbose_name_plural': 'Митапы',
            },
        ),
        migrations.CreateModel(
            name='Particiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(verbose_name='Telegram id')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Тема доклада')),
                ('start', models.TimeField(verbose_name='Время начала доклада')),
                ('end', models.TimeField(verbose_name='Время окончания доклада')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tg_bot.event', verbose_name='Митап')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tg_bot.particiant', verbose_name='Доклатчик')),
            ],
            options={
                'verbose_name': 'Митап',
                'verbose_name_plural': 'Митапы',
            },
        ),
    ]
