# Generated by Django 3.2.19 on 2023-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': 'Доклад', 'verbose_name_plural': 'Доклады'},
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.TimeField(verbose_name='Окончание митапа'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.TimeField(verbose_name='Начало митапа'),
        ),
    ]
