# Generated by Django 3.2.19 on 2023-06-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_auto_20230621_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='particiant',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'speaker'), (3, 'user')], default=3, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='particiant',
            name='telegram_id',
            field=models.IntegerField(unique=True, verbose_name='Telegram id'),
        ),
    ]
