# Generated by Django 3.2.19 on 2023-06-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_auto_20230623_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='particiant',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон'),
        ),
    ]
