# Generated by Django 3.2.19 on 2023-06-24 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0004_particiant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active_or_next_lecture',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='tg_bot.lecture', verbose_name='Лекция сейчас'),
        ),
    ]
