# Generated by Django 3.2.19 on 2023-06-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0005_event_active_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Доклад окончен'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tg_bot.particiant', verbose_name='Докладчик'),
        ),
    ]
